name: ğŸ¤– Android CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checar CÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Configurar JDK 17 para Ferramentas Android
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: ğŸ¤– Configurar SDK Android e Ferramentas
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true

      - name: ğŸ”’ Conceder PermissÃ£o ao gradlew
        run: chmod +x gradlew

      - name: â˜• Configurar JDK 11 para Projeto Android
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
        id: set_java_11

      - name: âœ… Rodar Testes UnitÃ¡rios
        env:
          JAVA_HOME: ${{ steps.set_java_11.outputs.java-home }}
        run: ./gradlew testDebugUnitTest